"""
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""
import timeit

from commons.numbers_ops import all_dividers


def get_triangle_of(n):
    return int(n * (n + 1) / 2)


def main():
    n = 1
    n_div = 0
    max_ndiv = 0
    while n_div <= 500:
        triangle = get_triangle_of(n)
        dividers = all_dividers(triangle)
        n_div = len(dividers)
        if n_div > max_ndiv:
            max_ndiv = n_div
            #print(f"{triangle} has {n_div} dividers.")
        n += 1
    print(f"The solution is {triangle}")


if __name__ == '__main__':
    t = timeit.timeit(main, number=1)
    print(f"Execution time: {t:.5f}s")
