"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


def main():
    p = 1
    n = 2
    curr_sum = 2
    while n <= 4e6:
        new_n = n + p
        p = n
        n = new_n
        if n % 2 == 0:
            curr_sum += n
    print(f'The solution is {curr_sum}')


if __name__ == '__main__':
    main()
